# Numpy functionalities

NumPy is a powerful Python library for numerical computing, offering a wide array of functionalities for array creation, 
manipulation, mathematical operations, and more.

Here's a comprehensive overview of its core functionalities:

# 1. Array Creation Functions

These functions help in creating arrays of various shapes and types:

1. np.array(): Creates an array from a list or tuple.

2. np.zeros(shape): Returns a new array of given shape and type, filled with zeros.

3. np.ones(shape): Returns a new array of given shape and type, filled with ones.

4. np.empty(shape): Returns a new array of given shape and type, without initializing entries.

5. np.arange(start, stop, step): Returns evenly spaced values within a given interval.

6. np.linspace(start, stop, num): Returns evenly spaced numbers over a specified interval.

7. np.eye(N): Returns a 2-D array with ones on the diagonal and zeros elsewhere.

8. np.full(shape, fill_value): Returns a new array of given shape and type, filled with fill_value.

# 2. Array Manipulation Functions

These functions allow reshaping, joining, and splitting arrays:

1. reshape(a, newshape): Gives a new shape to an array without changing its data.

2. ravel(a): Returns a contiguous flattened array.

3. transpose(a): Permutes the dimensions of an array.

4. concatenate((a1, a2, ...), axis=0): Joins a sequence of arrays along an existing axis.

5. split(ary, indices_or_sections, axis=0): Splits an array into multiple sub-arrays.

6. stack(arrays, axis=0): Joins a sequence of arrays along a new axis.

# 3. Mathematical Functions

NumPy provides a suite of mathematical functions for operations on arrays:

1. add(x1, x2): Adds arguments element-wise.

2. subtract(x1, x2): Subtracts arguments element-wise.

3. multiply(x1, x2): Multiplies arguments element-wise.

4. divide(x1, x2): Divides arguments element-wise.

5. power(x1, x2): First array elements raised to powers from second array, element-wise.

6. mod(x1, x2): Returns the element-wise remainder of division.

7. sqrt(x): Returns the non-negative square-root of an array, element-wise.

8. exp(x): Calculates the exponential of all elements in the input array.

9. log(x): Natural logarithm, element-wise.

10. log10(x): Base-10 logarithm, element-wise.

11. sin(x), cos(x), tan(x): Trigonometric functions.

12. arcsin(x), arccos(x), arctan(x): Inverse trigonometric functions.

13. sinh(x), cosh(x), tanh(x): Hyperbolic functions.

14. arcsinh(x), arccosh(x), arctanh(x): Inverse hyperbolic functions.

# 4. Statistical Functions

Functions for statistical operations on arrays:

1. mean(a): Computes the arithmetic mean.

2. median(a): Computes the median.

3. std(a): Computes the standard deviation.

4. var(a): Computes the variance.

5. min(a): Finds the minimum value.

6. max(a): Finds the maximum value.

7. argmin(a): Index of the minimum value.

8. argmax(a): Index of the maximum value.

9. percentile(a, q): Computes the qth percentile.

8. corrcoef(x, y): Pearson product-moment correlation coefficients.

9. cov(m): Covariance matrix.

# 5. Linear Algebra Functions

NumPy's linalg module provides linear algebra functions:

1. dot(a, b): Dot product of two arrays.

2. vdot(a, b): Dot product of two vectors.

3. inner(a, b): Inner product of two arrays.

4. matmul(a, b): Matrix product of two arrays.

5. det(a): Determinant of an array.

6. inv(a): Inverse of a matrix.

7. eig(a): Eigenvalues and right eigenvectors.

8. svd(a): Singular Value Decomposition.

9. solve(a, b): Solves a linear matrix equation.

10. lstsq(a, b): Computes the least-squares solution.

# 6. Random Number Generation

NumPy's random module offers functions for generating random numbers:

1. rand(d0, d1, ..., dn): Random values in a given shape.

2. randn(d0, d1, ..., dn): Samples from the standard normal distribution.

3. randint(low, high, size): Random integers from low (inclusive) to high (exclusive).

4. random(size): Random floats in the half-open interval [0.0, 1.0).

5. choice(a, size): Generates a random sample from a given 1-D array.

6. shuffle(x): Modifies a sequence in-place by shuffling its contents.

7. seed(s): Seeds the random number generator.


# 7. Logical and Comparison Functions

Functions for logical operations and comparisons:

1. where(condition, x, y): Return elements chosen from x or y depending on condition.

2. nonzero(a): Returns the indices of non-zero elements.

3. isnan(x): Tests element-wise for NaN and returns result as a boolean array.

4. isinf(x): Tests element-wise for positive or negative infinity.

5. isfinite(x): Tests element-wise for finiteness.

6. logical_and(x1, x2): Computes the truth value of x1 AND x2 element-wise.

7. logical_or(x1, x2): Computes the truth value of x1 OR x2 element-wise.

8. logical_not(x): Computes the truth value of NOT x element-wise.

9. logical_xor(x1, x2): Computes the truth value of x1 XOR x2 element-wise.

# 8. Input and Output Functions

Functions for reading and writing arrays to disk:

1. save(file, arr): Saves an array to a binary file in .npy format.

2. load(file): Loads an array from a .npy file.

3. savetxt(fname, X): Saves an array to a text file.

4. loadtxt(fname): Loads data from a text file.

5. genfromtxt(fname): Loads data from a text file, with missing values handled as specified.

6. fromfile(file): Constructs an array from data in a text or binary file.

7. tofile(fid): Writes an array to a file as text or binary.

# 9. Universal Functions (ufuncs)

Universal functions operate element-wise on arrays:

1. Arithmetic: add, subtract, multiply, divide, power, mod

2. Trigonometric: sin, cos, tan, arcsin, arccos, arctan

3. Exponential and logarithmic: exp, log, log10, log2

4. Comparison: greater, less, equal, not_equal, greater_equal, less_equal

5. Bitwise: bitwise_and, bitwise_or, bitwise_xor, invert

6. Other: absolute, floor, ceil, round, trunc

In [4]:
import numpy as np

In [5]:
l=[2,4,6,8,3,2,6]
l

[2, 4, 6, 8, 3, 2, 6]

In [6]:
# np.array(): Creates an array from a list or tuple.
a=np.array(l)
a

array([2, 4, 6, 8, 3, 2, 6])

In [7]:
# np.zeros(shape): Returns a new array of given shape and type, filled with zeros.
a1=np.zeros(5)
a1

array([0., 0., 0., 0., 0.])

In [8]:
# np.ones(shape): Returns a new array of given shape and type, filled with ones.
a2=np.ones(4)
a2

array([1., 1., 1., 1.])

In [9]:
# np.empty(shape): Returns a new array of given shape and type, without initializing entries.
a3=np.empty(6)
a3

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.22383221e-307,
       1.89146896e-307, 7.56571288e-307])

In [10]:
# np.arange(start, stop, step): Returns evenly spaced values within a given interval.
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [11]:
# np.linspace(start, stop, num): Returns evenly spaced numbers over a specified interval.
# it prints 7 evenly spaced numbers between 2 and 10 (inclusive).
np.linspace(2,10,7)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [12]:
# np.eye(N): Returns a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# np.full(shape, fill_value): Returns a new array of given shape and type, filled with fill_value.
np.full(8,5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [14]:
# reshape(a, newshape): Gives a new shape to an array without changing its data.
r=np.arange(3,15).reshape(3,4)
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [15]:
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [16]:
# ravel(a): Returns a contiguous flattened array.
np.ravel(r)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
# transpose(a): Permutes the dimensions of an array.
np.transpose(r) # rows become columns, columns become rows

array([[ 3,  7, 11],
       [ 4,  8, 12],
       [ 5,  9, 13],
       [ 6, 10, 14]])

In [18]:
r1=np.arange(1,13).reshape(3,4)
r1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [20]:
r1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
# concatenate((a1, a2, ...), axis=0): Joins a sequence of arrays along an existing axis.
np.concatenate((r,r1),axis=1)  # axis 0=row, 1=column

array([[ 3,  4,  5,  6,  1,  2,  3,  4],
       [ 7,  8,  9, 10,  5,  6,  7,  8],
       [11, 12, 13, 14,  9, 10, 11, 12]])

In [22]:
#split(ary, indices_or_sections, axis=0): Splits an array into multiple sub-arrays.
np.split(r,3,axis=0)

[array([[3, 4, 5, 6]]), array([[ 7,  8,  9, 10]]), array([[11, 12, 13, 14]])]

In [23]:
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [24]:
r1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
#stack(arrays, axis=0): Joins a sequence of arrays along a new axis.
np.stack((r,r1),axis=1)   # joins the columns of each array individually 

array([[[ 3,  4,  5,  6],
        [ 1,  2,  3,  4]],

       [[ 7,  8,  9, 10],
        [ 5,  6,  7,  8]],

       [[11, 12, 13, 14],
        [ 9, 10, 11, 12]]])

In [26]:
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [27]:
r1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
# add(x1, x2): Adds arguments element-wise.
np.add(r,r1)

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18],
       [20, 22, 24, 26]])

In [29]:
# subtract(x1, x2): Subtracts arguments element-wise.
np.subtract(r,r1)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [30]:
# multiply(x1, x2): Multiplies arguments element-wise.
np.multiply(r,r1)

array([[  3,   8,  15,  24],
       [ 35,  48,  63,  80],
       [ 99, 120, 143, 168]])

In [31]:
# divide(x1, x2): Divides arguments element-wise.
np.divide(r,r1)

array([[3.        , 2.        , 1.66666667, 1.5       ],
       [1.4       , 1.33333333, 1.28571429, 1.25      ],
       [1.22222222, 1.2       , 1.18181818, 1.16666667]])

In [32]:
# power(x1, x2): First array elements raised to powers from second array, element-wise.
np.power(r,r1)

array([[          3,          16,         125,        1296],
       [      16807,      262144,     4782969,   100000000],
       [-1937019605,  1787822080,  1159031605,   344068096]])

In [33]:
#mod(x1, x2): Returns the element-wise remainder of division.
np.mod(r,r1)

array([[0, 0, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [34]:
# sqrt(x): Returns the non-negative square-root of an array, element-wise.
np.sqrt(r)

array([[1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [35]:
# exp(x): Calculates the exponential of all elements in the input array.
np.exp(r)

array([[2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03, 2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06]])

In [36]:
# log(x): Natural logarithm, element-wise.
np.log(r)

array([[1.09861229, 1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733]])

In [37]:
#log10(x): Base-10 logarithm, element-wise. 
np.log10(r)

array([[0.47712125, 0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804]])

In [38]:
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [39]:
# sin(x), cos(x), tan(x): Trigonometric functions.

print(np.sin(r))

print(np.cos(r))

print(np.tan(r))

[[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736]]
[[-0.9899925  -0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026 -0.83907153]
 [ 0.0044257   0.84385396  0.90744678  0.13673722]]
[[-1.42546543e-01  1.15782128e+00 -3.38051501e+00 -2.91006191e-01]
 [ 8.71447983e-01 -6.79971146e+00 -4.52315659e-01  6.48360827e-01]
 [-2.25950846e+02 -6.35859929e-01  4.63021133e-01  7.24460662e+00]]


In [40]:
# arcsin(x), arccos(x), arctan(x): Inverse trigonometric functions.

print(np.arcsin(r))

print(np.arccos(r))

print(np.arctan(r))


[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
[[1.24904577 1.32581766 1.37340077 1.40564765]
 [1.42889927 1.44644133 1.46013911 1.47112767]
 [1.48013644 1.48765509 1.49402444 1.49948886]]


C:\Users\91630\AppData\Local\Temp\ipykernel_33272\1640613425.py:3: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(r))
C:\Users\91630\AppData\Local\Temp\ipykernel_33272\1640613425.py:5: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(r))


In [41]:
# sinh(x), cosh(x), tanh(x): Hyperbolic functions.

print(np.sinh(r))

print(np.cosh(r))

print(np.tanh(r))


[[1.00178749e+01 2.72899172e+01 7.42032106e+01 2.01713157e+02]
 [5.48316123e+02 1.49047883e+03 4.05154190e+03 1.10132329e+04]
 [2.99370708e+04 8.13773957e+04 2.21206696e+05 6.01302142e+05]]
[[1.00676620e+01 2.73082328e+01 7.42099485e+01 2.01715636e+02]
 [5.48317035e+02 1.49047916e+03 4.05154203e+03 1.10132329e+04]
 [2.99370709e+04 8.13773957e+04 2.21206696e+05 6.01302142e+05]]
[[0.99505475 0.9993293  0.9999092  0.99998771]
 [0.99999834 0.99999977 0.99999997 1.        ]
 [1.         1.         1.         1.        ]]


In [42]:
# arcsinh(x), arccosh(x), arctanh(x): Inverse hyperbolic functions.

print(np.arcsinh(r))

print(np.arccosh(r))

print(np.arctanh(r))


[[1.81844646 2.09471255 2.31243834 2.49177985]
 [2.64412076 2.77647228 2.89344399 2.99822295]
 [3.0931022  3.17978544 3.25957256 3.33347759]]
[[1.76274717 2.06343707 2.29243167 2.47788873]
 [2.63391579 2.76865938 2.88727095 2.99322285]
 [3.0889699  3.17631318 3.25661395 3.33092655]]
[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]


C:\Users\91630\AppData\Local\Temp\ipykernel_33272\3792555716.py:7: RuntimeWarning: invalid value encountered in arctanh
  print(np.arctanh(r))


In [43]:
# mean(a): Computes the arithmetic mean.
np.mean(r)

8.5

In [44]:
# median(a): Computes the median.
from numpy import *
d=array([3,5,4,22,35])
median(d)

5.0

In [45]:
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [46]:
# std(a): Computes the standard deviation.
np.std(r)

3.452052529534663

In [47]:
# var(a): Computes the variance.
np.var(r)

11.916666666666666

In [48]:
# min(a): Finds the minimum value.
np.min(r)

3

In [49]:
# max(a): Finds the maximum value.
np.max(r)

14

In [50]:
# argmin(a): Index of the minimum value.
np.argmin(r)

0

In [51]:
# argmax(a): Index of the maximum value.
np.argmax(r)

11

In [52]:
# percentile(a, q): Computes the qth percentile.
r3=np.percentile(r,r1)
r3

array([[3.11, 3.22, 3.33, 3.44],
       [3.55, 3.66, 3.77, 3.88],
       [3.99, 4.1 , 4.21, 4.32]])

In [53]:
# corrcoef(x, y): Pearson product-moment correlation coefficients.
np.corrcoef(r,r1)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [54]:
# cov(m): Covariance matrix.
np.cov(r)

array([[1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667]])

In [55]:
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [56]:
r1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
# dot(a, b): Dot product of two arrays.
np.dot(r,r1.T)  #Now you're doing (3×4) · (4×3) → Result shape: (3×3)

array([[ 50, 122, 194],
       [ 90, 226, 362],
       [130, 330, 530]])

In [58]:
# vdot(a, b): Dot product of two vectors.
np.vdot(r,r1)

806

In [59]:
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [60]:
r1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
# inner(a, b): Inner product of two arrays.
np.inner(r,r1)

array([[ 50, 122, 194],
       [ 90, 226, 362],
       [130, 330, 530]])

In [62]:
# matmul(a, b): Matrix product of two arrays.
np.matmul(r.T,r1)  #Now you're doing (3×4) · (4×3) → Result shape: (3×3)

array([[137, 158, 179, 200],
       [152, 176, 200, 224],
       [167, 194, 221, 248],
       [182, 212, 242, 272]])

In [63]:
# rand(d0, d1, ..., dn): Random values in a given shape.
np.random.rand(3,5)

array([[0.37323679, 0.21364719, 0.09830893, 0.91676731, 0.32245547],
       [0.36329171, 0.46816945, 0.09528808, 0.97919025, 0.88873521],
       [0.86714161, 0.28686825, 0.00187199, 0.34245283, 0.77456166]])

In [64]:
#randn(d0, d1, ..., dn): Samples from the standard normal distribution.
np.random.randn(5,3)

array([[-0.4223633 , -1.1097383 ,  0.41959071],
       [ 0.52612428, -0.82838783,  0.70221143],
       [ 0.05061707,  1.16429148, -0.11770413],
       [-0.90066819,  1.89574982, -0.86002139],
       [ 0.754169  , -0.56155888,  0.18213831]])

In [65]:
# randint(low, high, size): Random integers from low (inclusive) to high (exclusive).
np.random.randint(2,9,4)

array([3, 8, 5, 2])

In [66]:
r

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [67]:
# nonzero(a): Returns the indices of non-zero elements.
np.nonzero(r)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [68]:
# isnan(x): Tests element-wise for NaN and returns result as a boolean array.
np.isnan(r)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [69]:
# logical_and(x1, x2): Computes the truth value of x1 AND x2 element-wise.
np.logical_and(r,r1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
# logical_or(x1, x2): Computes the truth value of x1 OR x2 element-wise.
np.logical_or(r,r1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [71]:
# logical_not(x): Computes the truth value of NOT x element-wise.
np.logical_not(r)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [72]:
# logical_xor(x1, x2): Computes the truth value of x1 XOR x2 element-wise.
np.logical_xor(r,r1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [73]:
r3

array([[3.11, 3.22, 3.33, 3.44],
       [3.55, 3.66, 3.77, 3.88],
       [3.99, 4.1 , 4.21, 4.32]])

In [74]:
np.floor(r3)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 4., 4., 4.]])

In [75]:
np.ceil(r3)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 5., 5., 5.]])

In [76]:
np.round(r3)

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [77]:
# he truncated values of the input array — that is, it removes the decimal part and keeps 
# only the integer portion, toward zero.
np.trunc(r3)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 4., 4., 4.]])